#!/usr/bin/env python3
#-*- coding: utf-8 -*-

#=======================================================================================
# Imports
#=======================================================================================

import os
import sys
import functools
from lib.base import *
from lib.cappconfig import Defaults
from lib.capps import Capps
import lib.plugins
import plugins.capplibs.dash #TEST: plugin import.

#=======================================================================================
# Configuration
#=======================================================================================

defaults = Defaults()

#=======================================================================================
# Arguments & File Configuration
#=======================================================================================



#=======================================================================================
# Initialization
#=======================================================================================

# Make sure our configuration directories and files are ready to go.
try:
	os.makedirs(defaults.cappConfigDirPath)
except FileExistsError:
	pass

#=======================================================================================
# Library
#=======================================================================================

#==========================================================

#=======================================================================================
# Action
#=======================================================================================
print("[DEBUG][capman-mnsharing]", defaults.cappConfigDirPath)
capps = Capps(defaults.cappConfigDirPath)
allCapps = capps.getAll()
print(allCapps)